#ifndef CHIYOIMAGEBASE_GLOBAL_H
#define CHIYOIMAGEBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHIYOIMAGEBASE_LIBRARY)
#  define CHIYOIMAGEBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHIYOIMAGEBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHIYOIMAGEBASE_GLOBAL_H
