#ifndef CHIYOPLUGINS_GLOBAL_H
#define CHIYOPLUGINS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHIYOPLUGINS_LIBRARY)
#  define CHIYOPLUGINSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHIYOPLUGINSSHARED_EXPORT Q_DECL_IMPORT
#endif

#define CHIYO_PLUGINS_PATH "../ChiyoPlugins"

#define CHIYO_PLUGIN_ACTIONS_NAME_MAX_LENGTH 16384
#define CHIYO_PLUGIN_MAX_ACTIONS 256

#endif // CHIYOPLUGINS_GLOBAL_H
